app1/urls.py
from django.urls import path
from app1.views import *
from app1 import views
app_name='base1_app'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('login_form/',views.login_form,name='login_form'),
    path('featured/',views.featured,name='featured'),
    
]

app2/urls.py
from django.urls import path
from app1.views import *
from app2 import views
app_name='base2_app'

urlpatterns = [
    path('arrivals/',views.arrivals,name='arrivals'),
    path('blogs/',views.blogs,name='blogs'),
    path('reviews/',views.reviews,name='reviews'),
    
]

mockproject1/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')
def login_form(request):
    return render(request,'login_form.html')
def featured(request):
    return render(request,'featured.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def arrivals(request):
    return render(request,'arrivals.html')
def blogs(request):
    return render(request,'blogs.html')
def reviews(request):
    return render(request,'reviews.html')

templates/arrivals.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Arrivals</title>
    {% endblock %}
</head>
{% block body_block %}
<body>

    <!--section deals starts-->
<section class="deal">
    <div class="content">
        <h3>deal of the day</h3>
        <h1>upto 50% off</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus aliquam placeat esse vero, quisquam cum quidem tempora suscipit laborum adipisci debitis ipsam enim labore hic. Voluptatibus a esse repellendus.</p>
        <a href="#" class="btn">shop now</a>
    </div>
    <div class="image">
        <img  src="" alt="">
    </div>
</section>
    <!--arrivals section start here-->
<section class="arrivals" id="arrivals">
    <h1 class="heading"><span>new arrivals</span></h1>
    <div class="swiper arrivals-slider">
        <div class="swiper-wrapper">
            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured2.jpg' %}" alt="img1">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


            

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured4.jpg' %}" alt="img1">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured5.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="swiper arrivals-slider">
        <div class="swiper-wrapper">


            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured6.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured2.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


        

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured1.webp' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>

            
        </div>
    </div>
</section>
<!--arrivals section ends here-->



<section class="arrivals" id="arrivals">
    
    <div class="swiper arrivals-slider">
        <div class="swiper-wrapper">
            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured4.jpg' %}" alt="img1">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


            

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured1.webp' %}" alt="img1">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured3.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="swiper arrivals-slider">
        <div class="swiper-wrapper">


            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured6.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured7.jpg' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>


        

            <a href="#" class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/featured1.webp' %}" alt="">
                </div>
                <div class="content">
                    <h3>new arrivals</h3>
                    <div class="price">$15.90 <span>$20.99</span></div>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                </div>
            </a>

            
        </div>
    </div>
</section>
<!--arrivals section ends here-->


{% endblock %}
</body>
</html>

templates/blogs.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>blogs</title>
    {% endblock %}
</head>
{% block body_block %}
<body>
    <!--blog section starts here-->
<section class="blogs" id="blogs">
    <h1 class="heading"><span>our blogs</span></h1>
    <div class="swiper blogs-slider">
        <div class="swiper-wrapper">
            <div class="swiper-slide box" style="margin-right:20px;">
                <div class="image">
                    <img src="{% static 'images/blog1.jpg' %}" alt="image1">
                </div>
                <div class="content">
                    <h3>blog title goes here</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis nulla repellendus dolores eum distinctio, quam, unde te</p>
                    <a href="" class="btn">read more</a>
                </div>
            </div>

            <div class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/blog2.jpg' %}" alt="image2">
                </div>
                <div class="content">
                    <h3>blog title goes here</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis nulla repellendus dolores eum distinctio, quam, unde te</p>
                    <a href="" class="btn">read more</a>
                </div>
            </div>

            <div class="swiper-slide box">
                <div class="image">
                    <img src="{% static 'images/blog3.jpg' %}" alt="image3">
                </div>
                <div class="content">
                    <h3>blog title goes here</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis nulla repellendus dolores eum distinctio, quam, unde te</p>
                    <a href="" class="btn">read more</a>
                </div>
            </div>

            
            
        </div>
    </div>
</section>
<!--blog section ends here-->
</body>
{% endblock %}
</html>

templates/featured.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>featured</title>
    {% endblock %}
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    
</head>
{% block body_block %}
<body>
    <!--featured section stars here-->
<section class="featured" id="featured">
    <h1 class="heading"><span>Featured books</span></h1>

    <div class="swiper featured-slider">

        <div class="swiper-wrapper">

            <div class="swiper-slide box">
                <div class="icons">
                    <a href="#" class="bi bi-search"></a>
                    <a href="#" class="bi bi-heart"></a>
                    <a href="#" class="bi bi-eye-fill"></a>
                </div>
                <div class="image">
                    <img src="{% static 'images/featured1.webp' %}" alt="bookimg">
                </div>
                
               <div class="content">
                  <h3>featured book</h3>
                  <div class="price">$15.99 <span>$20.99</span></div>
                  <a href="" class="btn" >add to cart</a>
                    </div>
            </div>



            <div class="swiper-slide box">
                <div class="icons">
                    <a href="#" class="bi bi-search"></a>
                    <a href="#" class="bi bi-heart"></a>
                    <a href="#" class="bi bi-eye-fill"></a>
                </div>
                <div class="image">
                    <img src="{% static 'images/featured2.jpg' %}" alt="bookimg">
                </div>
            
                <div class="content">
                    <h3>featured book</h3>
                    <div class="price">$15.99 <span>$20.99</span></div>
                    <a href="" class="btn" >add to cart</a>
                </div>
            </div>

            <div class="swiper-slide box">
                <div class="icons">
                    <a href="#" class="bi bi-search"></a>
                    <a href="#" class="bi bi-heart"></a>
                    <a href="#" class="bi bi-eye-fill"></a>
                </div>
                <div class="image">
                    <img src="{% static 'images/featured3.jpg' %}" alt="bookimg">
                </div>
        
                <div class="content">
                    <h3>featured book</h3>
                    <div class="price">$15.99 <span>$20.99</span></div>
                    <a href="" class="btn" >add to cart</a>
                </div>
            </div>

            <div class="swiper-slide box">
                <div class="icons">
                    <a href="#" class="bi bi-search"></a>
                    <a href="#" class="bi bi-heart"></a>
                    <a href="#" class="bi bi-eye-fill"></a>
                </div>
                <div class="image">
                    <img src="{% static 'images/featured4.jpg' %}" alt="bookimg">
                </div>
    
                <div class="content">
                    <h3>featured book</h3>
                    <div class="price">$15.99 <span>$20.99</span></div>
                        <a href="" class="btn" >add to cart</a>
                </div>
            </div>

            

            

            
        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</section>
<!--featured section ends here-->

</body>
{% endblock %}
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title %}
    <title>Home</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    
    
</head>

<body>
    
<header class="header">
    <div class="header-1">
        <a href="#" class="logo"><i class="bi bi-journal-album"></i>bookly</a>
        <form action="" class="search-form">
            <input type="search" name="" placeholder="search here..." id="search-box">
            <label for="search-box" class="fas fa-search"></label>
            
        </form>
        <div class="icons">
            <div id="search-btn"></div>
            <a href="#" class="bi bi-heart"></a>
            <a href="#" class="bi bi-cart"></a>
            <a href="{% url 'base1_app:login_form' %}" id="login-btn"  class="bi bi-person"></a>
        </div>
    </div>


    <div class="header-2"  style="text-align: center;">
        <nav class="navbar" style="display: inline-block;"  style="text-align: center;">
            <a href="{% url 'base1_app:index' %}" style="text-decoration: none; "  style="text-align: center;">home</a>
            <a href="{% url 'base1_app:featured' %}" style="text-decoration: none;"  style="text-align: center;">Featured</a>
            <a href="{% url 'base2_app:arrivals' %}" style="text-decoration: none;"  style="text-align: center;">Arrivals</a>
            <a href="{% url 'base2_app:reviews' %}" style="text-decoration: none;"  style="text-align: center;">Reviews</a>
            <a href="{% url 'base2_app:blogs' %}" style="text-decoration: none;"  style="text-align: center;">Blog</a>
            
        </nav>
    </div>
</header>

    <!-- bottom navbar-->

    <nav class="bottom-navbar">
        <a href="{% url 'base1_app:index' %}" class="bi bi-house"></a>
        <a href="{% url 'base1_app:featured' %}" class="bi bi-list-ul"></a>
        <a href="{% url 'base2_app:arrivals' %}" class="bi bi-tags-fill"></a>
        <a href="{% url 'base2_app:reviews' %}" class="bi bi-chat-square-fill"></a>
        <a href="{% url 'base2_app:blogs' %}"  class="bi bi-wechat"></a>
        
    </nav>
    {% block body_block %}
<!--home section-->
    <section class="home" id="home">
        <div class="row">
          <div class="content">
            <h3>upto 75% off</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita quam quia harum dolorem, error ipsum, quo aperiam iure unde culpa magni quis earum quidem nisi? Soluta, amet! Accusantium, ducimus laborum!</p>
            <a href="#" class="btn">shop now</a>
          </div>

         <div class="swiper books-slider">
            <div class="swiper-wrapper">
             <a href="#" class="swiper-slide"><img src="" alt=""></a>
             <a href="#"  class="swiper-slide"><img src="" alt=""></a>
             <a href="#"  class="swiper-slide"><img src="" alt=""></a>
             <a href="#"  class="swiper-slide"><img src="" alt=""></a>
             <a href="#"  class="swiper-slide"><img src="" alt=""></a>
             <a href="#" class="swiper-slide"><img src="" alt=""></a>

             
            </div>
            <img src="" class="stand" alt="">
         
        </div>
        </div>

    </section>

<!--icon section starts-->

<section class="icons-container">
    <div class="icons">
        <i class="bi bi-truck-flatbed"></i>
        <div class="content">
            <h3>fast shipping</h3>
            <p>order over$100</p>
        </div>
    </div>

    <div class="icons">
        <i class="bi bi-lock-fill"></i>
        <div class="content">
            <h3>secure paayments</h3>
            <p>100 secure payments</p>
        </div>
    </div>

    <div class="icons">
        <i class="bi bi-arrow-clockwise"></i>
        <div class="content">
            <h3>easy returns</h3>
            <p>10 days returns</p>
        </div>
    </div>

    <div class="icons">
        <i class="bi bi-headset"></i>
        <div class="content">
            <h3>24/7 support</h3>
            <p>call us anytime</p>
        </div>
    </div>


</section>

<!--icon sectiocton-->


<!--newsletter section starts here-->
<section class="newsletter">
    <form action="">
        <h3>subscibe for latest update</h3>
        <input type="email" name="" placeholder="enter your mail" id="" class="box">
        <input type="submit" value="subscribe" class="btn">
    </form>
</section>
<!--newsletter section starts here-->


<!--section deals starts-->
<section class="deal">
    <div class="content">
        <h3>deal of the day</h3>
        <h1>upto 50% off</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus aliquam placeat esse vero, quisquam cum quidem tempora suscipit laborum adipisci debitis ipsam enim labore hic. Voluptatibus a esse repellendus.</p>
        <a href="#" class="btn">shop now</a>
    </div>
    <div class="image">
        <img  src="" alt="">
    </div>
</section>
<!--section deals ends-->
{% endblock %}
<hr>
   <!--footer section starts here-->
   <section class="footer">
    <div class="box-container">
        <div class="box">
            <h3>our locations</h3>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>india</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>usa</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>russia</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>france</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>japan</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-geo-alt"></i>africa</a>
        </div>
        <div class="box">
            <h3>quick links</h3>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>home</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>featured</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>arrivals</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>reviews</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>blogs</a>
            
        </div>

        <div class="box">
            <h3>extra links</h3>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>account info</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>ordered items</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>privacy policy</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>payment methods</a>
            <a href="" style="text-decoration: none;"><i class="bi bi-arrow-right"></i>our services</a>
            
        </div>

        <div class="box">
            <h3> contact info</h3>
            <a href=""  style="text-decoration: none;"><i class="bi bi-telephone"></i>+123-456-7890</a>
            <a href=""  style="text-decoration: none;"><i class="bi bi-telephone"></i>+111-222-333</a>
            <a href=""  style="text-decoration: none;"><i class="bi bi-envelope"></i>sri@gmail.com</a>
            
            
        </div>
    </div>

        <div class="share">
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-twitter"></i></a>
            <a href=""><i class="bi bi-pinterest"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
            
        </div>

        <div class="credit"><span></span>all rights reserved!</span></div>


    
</section>

<!--footer section ends here-->




















    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</body>
</html>

templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>Forms</title>
    <style>
        body{
            background-image:linear-gradient(45deg,rgb(141, 188, 141),rgb(18, 43, 23))
        }
        .container
        {
            background-color: black;
            text-align: center;
            width:500px;
            margin:100px auto;
            padding:50px;
            border-radius: 20px;
            
        }
        button
        {
            padding:10px 20px;
            background-color:red;
            color:white;
            border-radius: 20px;
        }
        
        .child
        {
            margin-top:20px;
        }
        label
        {
            
            color:white;
        }
        .one{
            width:210px;
            border-radius: 20px;
            padding:10px;
            margin:10px;
        }
        .two
        {
            width:500px;
            border-radius: 20px;
            padding:5px;
        }
        h2
        {
            color:white;
            padding:10px;
        }
        .three
        {
            width:500px;
            border-radius:20px;
        }
        .ele
        {
            text-align: start;
            
        }
        .parent
        {
            border:2px solid black;
            width:700px;
        }
    </style>
</head>
<body>
    <forms>
        <div class="container">
            <h2>Contact Us</h2>
            <div class="child">
                <table>
                    <tr>
                        <td><label class="ele">Full name</label></td>
                        
                    </tr>
                </table>

                
                <table>
                    <tr>
                        <td><input class="one" type="text" id="" ></td>
                        <td><input class="one" type="text" id="" ></td>    
                    </tr>
                    
                </table>
                <table>
                    <tr>
                        <td><label for="">first</label></td>
                        <td><label for="">last</label></td>
                    </tr>
                </table>

            </div>
            <div class="child">
                <table>
                    <tr>
                        <td><label class="ele">Email</label></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><input class="two" type="email" id=""></td>
                    </tr>
                </table>
                <div class="child">
                    <table>
                        <tr>
                            <td><label class="ele">Leave us few words</label></td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <td><textarea class="three"></textarea></td>
                        </tr>
                    </table>


                </div>
                

            </div>
            <div class="child">
                <button>submit</button>

            </div>

        </div>
    </forms>
    
</body>
</html>